### ISSUE TITLE
pypi package/install

### ISSUE THREAD

**Issue by dwasyl** [litchfield/django-autocomplete-light-selectize#1]
Hey there,

I tried doing a pip install of this package and I noticed that the static files weren't installed into the package directory.

I manually added the imports to the dal package, although I'm still getting selectize errors on load. Are there any special tricks (beyond changing Select2 to Selectize for widgets and mixins).

**Comment by n3storm** [comment]
See my fork or pull request. https://github.com/EstudioNexos/django-autocomplete-light-selectize

**Comment by litchfield** [comment]
Merged- thanks!
